'use client';

import { useMemo } from 'react';
import { Vector3 } from 'three';
import { buildJourney } from '@/lib/curve';

/**
 * 7. THE STAIRS — the night-to-dawn transition.
 *
 * The steps are generated by sampling the camera curve itself between the
 * `stairs` and `rooftop` marks and dropping a tread 1.7m below each sample. That
 * guarantees the geometry follows wherever the path goes: retune a waypoint in
 * data/journey.ts and the staircase moves with the camera instead of drifting
 * out from under it.
 */

const STEP_COUNT = 30;
const EYE_HEIGHT = 1.7;

export function Stairs() {
  const steps = useMemo(() => {
    const { curve, marks } = buildJourney();
    const from = marks.stairs;
    const to = marks.rooftop;

    const treads: { position: [number, number, number]; rotationY: number }[] = [];

    for (let i = 0; i <= STEP_COUNT; i++) {
      const t = i / STEP_COUNT;
      const u = from + (to - from) * t;
      const point = curve.getPointAt(u, new Vector3());
      const ahead = curve.getPointAt(Math.min(u + 0.004, 1), new Vector3());

      // Face each tread along the direction of travel so the flight banks
      // through the turn instead of shearing.
      const rotationY = Math.atan2(ahead.x - point.x, ahead.z - point.z);

      treads.push({
        position: [point.x, point.y - EYE_HEIGHT, point.z],
        rotationY,
      });
    }

    return treads;
  }, []);

  return (
    <group>
      {/* ── Treads ───────────────────────────────────────────────────────── */}
      {steps.map((step, i) => (
        <group key={i} position={step.position} rotation={[0, step.rotationY, 0]}>
          <mesh castShadow receiveShadow>
            <boxGeometry args={[3.2, 0.16, 0.9]} />
            <meshStandardMaterial
              color="#1B1D24"
              roughness={0.82}
              metalness={0.15}
            />
          </mesh>
          {/* Every fourth step gets an inset light — the climb reads as a
              runway pulling you upward. */}
          {i % 4 === 0 ? (
            <mesh position={[0, 0.09, 0.38]}>
              <boxGeometry args={[2.6, 0.02, 0.05]} />
              <meshStandardMaterial
                color="#FFB877"
                emissive="#FFB877"
                emissiveIntensity={2.6}
                toneMapped={false}
              />
            </mesh>
          ) : null}
        </group>
      ))}

      {/* ── Side walls, closing the stairwell in ─────────────────────────── */}
      {steps
        .filter((_, i) => i % 2 === 0)
        .map((step, i) => (
          <group key={i} position={step.position} rotation={[0, step.rotationY, 0]}>
            {[-1, 1].map((side) => (
              <mesh key={side} position={[side * 1.9, 1.6, 0]}>
                <boxGeometry args={[0.3, 4.2, 1.8]} />
                <meshStandardMaterial color="#171A22" roughness={0.98} />
              </mesh>
            ))}
          </group>
        ))}

      {/* ── The light at the top ─────────────────────────────────────────── */}
      {/* A cool dawn source above the last step, so the climb visibly heads
          toward daylight rather than just getting less dark. */}

    </group>
  );
}
